// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Decimate one chart tile from the retained session handle. `tier` 0 = raw;
/// `tile_index` selects the 1024-bucket window. All-NaN for an absent channel.
Future<Float64List> decimateTile(
        {required SessionHandle handle,
        required String channelId,
        required int tier,
        required int tileIndex}) =>
    RustLib.instance.api.crateChartDecimationDecimateTile(
        handle: handle, channelId: channelId, tier: tier, tileIndex: tileIndex);
