// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mirror of [`idl_rs::fft::Averaging`] for FRB codegen.
enum Averaging {
  mean,
  median,
  ;
}

/// Mirror of [`idl_rs::fft::Detrend`] for FRB codegen.
enum Detrend {
  none,
  mean,
  linear,
  ;
}

/// Mirror of [`idl_rs::fft::FftWindow`] for FRB codegen.
enum FftWindow {
  rectangular,
  hann,
  hamming,
  ;
}

/// Mirror of [`idl_rs::fft::Scaling`] for FRB codegen.
enum Scaling {
  magnitude,
  density,
  ;
}

/// Mirror of [`idl_rs::fft::WelchResult`] for FRB codegen.
class WelchResult {
  final Float64List freqsHz;
  final Float64List values;

  const WelchResult({
    required this.freqsHz,
    required this.values,
  });

  @override
  int get hashCode => freqsHz.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WelchResult &&
          runtimeType == other.runtimeType &&
          freqsHz == other.freqsHz &&
          values == other.values;
}
