// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'chart_decimation.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'fft.dart';
import 'frb_generated.dart';
import 'histogram.dart';
import 'laps.dart';
import 'lib.dart';
import 'math.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'scatter.dart';
import 'session.dart';
import 'spectrogram.dart';
import 'table.dart';
import 'tracks.dart';
import 'video.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SessionHandlePtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_SessionHandlePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SessionHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandlePtr;

  @protected
  SessionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
          dynamic raw);

  @protected
  SessionHandle dco_decode_RustOpaque_SessionHandle(dynamic raw);

  @protected
  SessionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Averaging dco_decode_averaging(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ChannelBounds dco_decode_box_autoadd_channel_bounds(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LapTimingArg dco_decode_box_autoadd_lap_timing_arg(dynamic raw);

  @protected
  MathLapCtxArg dco_decode_box_autoadd_math_lap_ctx_arg(dynamic raw);

  @protected
  MathOverlayArg dco_decode_box_autoadd_math_overlay_arg(dynamic raw);

  @protected
  RowContext dco_decode_box_autoadd_row_context(dynamic raw);

  @protected
  SessionMetaInput dco_decode_box_autoadd_session_meta_input(dynamic raw);

  @protected
  SuspensionConfig dco_decode_box_autoadd_suspension_config(dynamic raw);

  @protected
  TableModel dco_decode_box_autoadd_table_model(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Cell dco_decode_cell(dynamic raw);

  @protected
  CellResult dco_decode_cell_result(dynamic raw);

  @protected
  ChannelBounds dco_decode_channel_bounds(dynamic raw);

  @protected
  ChannelInput dco_decode_channel_input(dynamic raw);

  @protected
  ChannelMeta dco_decode_channel_meta(dynamic raw);

  @protected
  Column dco_decode_column(dynamic raw);

  @protected
  Detrend dco_decode_detrend(dynamic raw);

  @protected
  EvalStoredMeta dco_decode_eval_stored_meta(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FftWindow dco_decode_fft_window(dynamic raw);

  @protected
  FitLap dco_decode_fit_lap(dynamic raw);

  @protected
  FitSport dco_decode_fit_sport(dynamic raw);

  @protected
  GateArg dco_decode_gate_arg(dynamic raw);

  @protected
  GpsFixArg dco_decode_gps_fix_arg(dynamic raw);

  @protected
  HistogramResult dco_decode_histogram_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Lap dco_decode_lap(dynamic raw);

  @protected
  LapTimingArg dco_decode_lap_timing_arg(dynamic raw);

  @protected
  LapTimingKind dco_decode_lap_timing_kind(dynamic raw);

  @protected
  List<SessionHandle> dco_decode_list_RustOpaque_SessionHandle(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<Cell> dco_decode_list_cell(dynamic raw);

  @protected
  List<CellResult> dco_decode_list_cell_result(dynamic raw);

  @protected
  List<ChannelInput> dco_decode_list_channel_input(dynamic raw);

  @protected
  List<ChannelMeta> dco_decode_list_channel_meta(dynamic raw);

  @protected
  List<Column> dco_decode_list_column(dynamic raw);

  @protected
  List<FitLap> dco_decode_list_fit_lap(dynamic raw);

  @protected
  List<GpsFixArg> dco_decode_list_gps_fix_arg(dynamic raw);

  @protected
  List<Lap> dco_decode_list_lap(dynamic raw);

  @protected
  List<List<Cell>> dco_decode_list_list_cell(dynamic raw);

  @protected
  List<List<CellResult>> dco_decode_list_list_cell_result(dynamic raw);

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw);

  @protected
  List<MathChannelDefArg> dco_decode_list_math_channel_def_arg(dynamic raw);

  @protected
  List<NeutralZoneArg> dco_decode_list_neutral_zone_arg(dynamic raw);

  @protected
  List<NeutralZoneVisit> dco_decode_list_neutral_zone_visit(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(double, double)> dco_decode_list_record_f_64_f_64(dynamic raw);

  @protected
  List<Row> dco_decode_list_row(dynamic raw);

  @protected
  List<Sector> dco_decode_list_sector(dynamic raw);

  @protected
  List<SectorGateArg> dco_decode_list_sector_gate_arg(dynamic raw);

  @protected
  List<TrackArg> dco_decode_list_track_arg(dynamic raw);

  @protected
  List<VisitWindow> dco_decode_list_visit_window(dynamic raw);

  @protected
  MathChannelDefArg dco_decode_math_channel_def_arg(dynamic raw);

  @protected
  MathEvalFailure dco_decode_math_eval_failure(dynamic raw);

  @protected
  MathEvalFailureKind dco_decode_math_eval_failure_kind(dynamic raw);

  @protected
  MathLapCtxArg dco_decode_math_lap_ctx_arg(dynamic raw);

  @protected
  MathOverlayArg dco_decode_math_overlay_arg(dynamic raw);

  @protected
  NeutralZoneArg dco_decode_neutral_zone_arg(dynamic raw);

  @protected
  NeutralZoneVisit dco_decode_neutral_zone_visit(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ChannelBounds? dco_decode_opt_box_autoadd_channel_bounds(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MathOverlayArg? dco_decode_opt_box_autoadd_math_overlay_arg(dynamic raw);

  @protected
  RowContext? dco_decode_opt_box_autoadd_row_context(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Float64List? dco_decode_opt_list_prim_f_64_strict(dynamic raw);

  @protected
  ParseErrorKind dco_decode_parse_error_kind(dynamic raw);

  @protected
  ParseFailure dco_decode_parse_failure(dynamic raw);

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw);

  @protected
  Row dco_decode_row(dynamic raw);

  @protected
  RowContext dco_decode_row_context(dynamic raw);

  @protected
  Scaling dco_decode_scaling(dynamic raw);

  @protected
  ScatterDensity dco_decode_scatter_density(dynamic raw);

  @protected
  ScatterPoints dco_decode_scatter_points(dynamic raw);

  @protected
  Sector dco_decode_sector(dynamic raw);

  @protected
  SectorGateArg dco_decode_sector_gate_arg(dynamic raw);

  @protected
  SessionMeta dco_decode_session_meta(dynamic raw);

  @protected
  SessionMetaInput dco_decode_session_meta_input(dynamic raw);

  @protected
  SliceLapResult dco_decode_slice_lap_result(dynamic raw);

  @protected
  SpectrogramResult dco_decode_spectrogram_result(dynamic raw);

  @protected
  SuspensionConfig dco_decode_suspension_config(dynamic raw);

  @protected
  SuspensionEstimateFailure dco_decode_suspension_estimate_failure(dynamic raw);

  @protected
  SuspensionEstimateMeta dco_decode_suspension_estimate_meta(dynamic raw);

  @protected
  TableModel dco_decode_table_model(dynamic raw);

  @protected
  TrackArg dco_decode_track_arg(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoFailure dco_decode_video_failure(dynamic raw);

  @protected
  VideoFailureKind dco_decode_video_failure_kind(dynamic raw);

  @protected
  VideoInfo dco_decode_video_info(dynamic raw);

  @protected
  VideoSyncMethod dco_decode_video_sync_method(dynamic raw);

  @protected
  VideoSyncOutcome dco_decode_video_sync_outcome(dynamic raw);

  @protected
  VisitWindow dco_decode_visit_window(dynamic raw);

  @protected
  WelchResult dco_decode_welch_result(dynamic raw);

  @protected
  SessionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
          SseDeserializer deserializer);

  @protected
  SessionHandle sse_decode_RustOpaque_SessionHandle(
      SseDeserializer deserializer);

  @protected
  SessionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Averaging sse_decode_averaging(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ChannelBounds sse_decode_box_autoadd_channel_bounds(
      SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LapTimingArg sse_decode_box_autoadd_lap_timing_arg(
      SseDeserializer deserializer);

  @protected
  MathLapCtxArg sse_decode_box_autoadd_math_lap_ctx_arg(
      SseDeserializer deserializer);

  @protected
  MathOverlayArg sse_decode_box_autoadd_math_overlay_arg(
      SseDeserializer deserializer);

  @protected
  RowContext sse_decode_box_autoadd_row_context(SseDeserializer deserializer);

  @protected
  SessionMetaInput sse_decode_box_autoadd_session_meta_input(
      SseDeserializer deserializer);

  @protected
  SuspensionConfig sse_decode_box_autoadd_suspension_config(
      SseDeserializer deserializer);

  @protected
  TableModel sse_decode_box_autoadd_table_model(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Cell sse_decode_cell(SseDeserializer deserializer);

  @protected
  CellResult sse_decode_cell_result(SseDeserializer deserializer);

  @protected
  ChannelBounds sse_decode_channel_bounds(SseDeserializer deserializer);

  @protected
  ChannelInput sse_decode_channel_input(SseDeserializer deserializer);

  @protected
  ChannelMeta sse_decode_channel_meta(SseDeserializer deserializer);

  @protected
  Column sse_decode_column(SseDeserializer deserializer);

  @protected
  Detrend sse_decode_detrend(SseDeserializer deserializer);

  @protected
  EvalStoredMeta sse_decode_eval_stored_meta(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FftWindow sse_decode_fft_window(SseDeserializer deserializer);

  @protected
  FitLap sse_decode_fit_lap(SseDeserializer deserializer);

  @protected
  FitSport sse_decode_fit_sport(SseDeserializer deserializer);

  @protected
  GateArg sse_decode_gate_arg(SseDeserializer deserializer);

  @protected
  GpsFixArg sse_decode_gps_fix_arg(SseDeserializer deserializer);

  @protected
  HistogramResult sse_decode_histogram_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Lap sse_decode_lap(SseDeserializer deserializer);

  @protected
  LapTimingArg sse_decode_lap_timing_arg(SseDeserializer deserializer);

  @protected
  LapTimingKind sse_decode_lap_timing_kind(SseDeserializer deserializer);

  @protected
  List<SessionHandle> sse_decode_list_RustOpaque_SessionHandle(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<Cell> sse_decode_list_cell(SseDeserializer deserializer);

  @protected
  List<CellResult> sse_decode_list_cell_result(SseDeserializer deserializer);

  @protected
  List<ChannelInput> sse_decode_list_channel_input(
      SseDeserializer deserializer);

  @protected
  List<ChannelMeta> sse_decode_list_channel_meta(SseDeserializer deserializer);

  @protected
  List<Column> sse_decode_list_column(SseDeserializer deserializer);

  @protected
  List<FitLap> sse_decode_list_fit_lap(SseDeserializer deserializer);

  @protected
  List<GpsFixArg> sse_decode_list_gps_fix_arg(SseDeserializer deserializer);

  @protected
  List<Lap> sse_decode_list_lap(SseDeserializer deserializer);

  @protected
  List<List<Cell>> sse_decode_list_list_cell(SseDeserializer deserializer);

  @protected
  List<List<CellResult>> sse_decode_list_list_cell_result(
      SseDeserializer deserializer);

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
      SseDeserializer deserializer);

  @protected
  List<MathChannelDefArg> sse_decode_list_math_channel_def_arg(
      SseDeserializer deserializer);

  @protected
  List<NeutralZoneArg> sse_decode_list_neutral_zone_arg(
      SseDeserializer deserializer);

  @protected
  List<NeutralZoneVisit> sse_decode_list_neutral_zone_visit(
      SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(double, double)> sse_decode_list_record_f_64_f_64(
      SseDeserializer deserializer);

  @protected
  List<Row> sse_decode_list_row(SseDeserializer deserializer);

  @protected
  List<Sector> sse_decode_list_sector(SseDeserializer deserializer);

  @protected
  List<SectorGateArg> sse_decode_list_sector_gate_arg(
      SseDeserializer deserializer);

  @protected
  List<TrackArg> sse_decode_list_track_arg(SseDeserializer deserializer);

  @protected
  List<VisitWindow> sse_decode_list_visit_window(SseDeserializer deserializer);

  @protected
  MathChannelDefArg sse_decode_math_channel_def_arg(
      SseDeserializer deserializer);

  @protected
  MathEvalFailure sse_decode_math_eval_failure(SseDeserializer deserializer);

  @protected
  MathEvalFailureKind sse_decode_math_eval_failure_kind(
      SseDeserializer deserializer);

  @protected
  MathLapCtxArg sse_decode_math_lap_ctx_arg(SseDeserializer deserializer);

  @protected
  MathOverlayArg sse_decode_math_overlay_arg(SseDeserializer deserializer);

  @protected
  NeutralZoneArg sse_decode_neutral_zone_arg(SseDeserializer deserializer);

  @protected
  NeutralZoneVisit sse_decode_neutral_zone_visit(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ChannelBounds? sse_decode_opt_box_autoadd_channel_bounds(
      SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MathOverlayArg? sse_decode_opt_box_autoadd_math_overlay_arg(
      SseDeserializer deserializer);

  @protected
  RowContext? sse_decode_opt_box_autoadd_row_context(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Float64List? sse_decode_opt_list_prim_f_64_strict(
      SseDeserializer deserializer);

  @protected
  ParseErrorKind sse_decode_parse_error_kind(SseDeserializer deserializer);

  @protected
  ParseFailure sse_decode_parse_failure(SseDeserializer deserializer);

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer);

  @protected
  Row sse_decode_row(SseDeserializer deserializer);

  @protected
  RowContext sse_decode_row_context(SseDeserializer deserializer);

  @protected
  Scaling sse_decode_scaling(SseDeserializer deserializer);

  @protected
  ScatterDensity sse_decode_scatter_density(SseDeserializer deserializer);

  @protected
  ScatterPoints sse_decode_scatter_points(SseDeserializer deserializer);

  @protected
  Sector sse_decode_sector(SseDeserializer deserializer);

  @protected
  SectorGateArg sse_decode_sector_gate_arg(SseDeserializer deserializer);

  @protected
  SessionMeta sse_decode_session_meta(SseDeserializer deserializer);

  @protected
  SessionMetaInput sse_decode_session_meta_input(SseDeserializer deserializer);

  @protected
  SliceLapResult sse_decode_slice_lap_result(SseDeserializer deserializer);

  @protected
  SpectrogramResult sse_decode_spectrogram_result(SseDeserializer deserializer);

  @protected
  SuspensionConfig sse_decode_suspension_config(SseDeserializer deserializer);

  @protected
  SuspensionEstimateFailure sse_decode_suspension_estimate_failure(
      SseDeserializer deserializer);

  @protected
  SuspensionEstimateMeta sse_decode_suspension_estimate_meta(
      SseDeserializer deserializer);

  @protected
  TableModel sse_decode_table_model(SseDeserializer deserializer);

  @protected
  TrackArg sse_decode_track_arg(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoFailure sse_decode_video_failure(SseDeserializer deserializer);

  @protected
  VideoFailureKind sse_decode_video_failure_kind(SseDeserializer deserializer);

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer);

  @protected
  VideoSyncMethod sse_decode_video_sync_method(SseDeserializer deserializer);

  @protected
  VideoSyncOutcome sse_decode_video_sync_outcome(SseDeserializer deserializer);

  @protected
  VisitWindow sse_decode_visit_window(SseDeserializer deserializer);

  @protected
  WelchResult sse_decode_welch_result(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
          SessionHandle self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_SessionHandle(
      SessionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
          SessionHandle self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_averaging(Averaging self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_channel_bounds(
      ChannelBounds self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lap_timing_arg(
      LapTimingArg self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_math_lap_ctx_arg(
      MathLapCtxArg self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_math_overlay_arg(
      MathOverlayArg self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_row_context(
      RowContext self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_meta_input(
      SessionMetaInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_suspension_config(
      SuspensionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_table_model(
      TableModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_cell(Cell self, SseSerializer serializer);

  @protected
  void sse_encode_cell_result(CellResult self, SseSerializer serializer);

  @protected
  void sse_encode_channel_bounds(ChannelBounds self, SseSerializer serializer);

  @protected
  void sse_encode_channel_input(ChannelInput self, SseSerializer serializer);

  @protected
  void sse_encode_channel_meta(ChannelMeta self, SseSerializer serializer);

  @protected
  void sse_encode_column(Column self, SseSerializer serializer);

  @protected
  void sse_encode_detrend(Detrend self, SseSerializer serializer);

  @protected
  void sse_encode_eval_stored_meta(
      EvalStoredMeta self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fft_window(FftWindow self, SseSerializer serializer);

  @protected
  void sse_encode_fit_lap(FitLap self, SseSerializer serializer);

  @protected
  void sse_encode_fit_sport(FitSport self, SseSerializer serializer);

  @protected
  void sse_encode_gate_arg(GateArg self, SseSerializer serializer);

  @protected
  void sse_encode_gps_fix_arg(GpsFixArg self, SseSerializer serializer);

  @protected
  void sse_encode_histogram_result(
      HistogramResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_lap(Lap self, SseSerializer serializer);

  @protected
  void sse_encode_lap_timing_arg(LapTimingArg self, SseSerializer serializer);

  @protected
  void sse_encode_lap_timing_kind(LapTimingKind self, SseSerializer serializer);

  @protected
  void sse_encode_list_RustOpaque_SessionHandle(
      List<SessionHandle> self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell(List<Cell> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell_result(
      List<CellResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_input(
      List<ChannelInput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_meta(
      List<ChannelMeta> self, SseSerializer serializer);

  @protected
  void sse_encode_list_column(List<Column> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fit_lap(List<FitLap> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gps_fix_arg(
      List<GpsFixArg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lap(List<Lap> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_cell(
      List<List<Cell>> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_cell_result(
      List<List<CellResult>> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_f_64_strict(
      List<Float64List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_math_channel_def_arg(
      List<MathChannelDefArg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_neutral_zone_arg(
      List<NeutralZoneArg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_neutral_zone_visit(
      List<NeutralZoneVisit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_loose(
      List<double> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_f_64_f_64(
      List<(double, double)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_row(List<Row> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sector(List<Sector> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sector_gate_arg(
      List<SectorGateArg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_track_arg(List<TrackArg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_visit_window(
      List<VisitWindow> self, SseSerializer serializer);

  @protected
  void sse_encode_math_channel_def_arg(
      MathChannelDefArg self, SseSerializer serializer);

  @protected
  void sse_encode_math_eval_failure(
      MathEvalFailure self, SseSerializer serializer);

  @protected
  void sse_encode_math_eval_failure_kind(
      MathEvalFailureKind self, SseSerializer serializer);

  @protected
  void sse_encode_math_lap_ctx_arg(
      MathLapCtxArg self, SseSerializer serializer);

  @protected
  void sse_encode_math_overlay_arg(
      MathOverlayArg self, SseSerializer serializer);

  @protected
  void sse_encode_neutral_zone_arg(
      NeutralZoneArg self, SseSerializer serializer);

  @protected
  void sse_encode_neutral_zone_visit(
      NeutralZoneVisit self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_channel_bounds(
      ChannelBounds? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_math_overlay_arg(
      MathOverlayArg? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_row_context(
      RowContext? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_f_64_strict(
      Float64List? self, SseSerializer serializer);

  @protected
  void sse_encode_parse_error_kind(
      ParseErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_parse_failure(ParseFailure self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_64_f_64(
      (double, double) self, SseSerializer serializer);

  @protected
  void sse_encode_row(Row self, SseSerializer serializer);

  @protected
  void sse_encode_row_context(RowContext self, SseSerializer serializer);

  @protected
  void sse_encode_scaling(Scaling self, SseSerializer serializer);

  @protected
  void sse_encode_scatter_density(
      ScatterDensity self, SseSerializer serializer);

  @protected
  void sse_encode_scatter_points(ScatterPoints self, SseSerializer serializer);

  @protected
  void sse_encode_sector(Sector self, SseSerializer serializer);

  @protected
  void sse_encode_sector_gate_arg(SectorGateArg self, SseSerializer serializer);

  @protected
  void sse_encode_session_meta(SessionMeta self, SseSerializer serializer);

  @protected
  void sse_encode_session_meta_input(
      SessionMetaInput self, SseSerializer serializer);

  @protected
  void sse_encode_slice_lap_result(
      SliceLapResult self, SseSerializer serializer);

  @protected
  void sse_encode_spectrogram_result(
      SpectrogramResult self, SseSerializer serializer);

  @protected
  void sse_encode_suspension_config(
      SuspensionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_suspension_estimate_failure(
      SuspensionEstimateFailure self, SseSerializer serializer);

  @protected
  void sse_encode_suspension_estimate_meta(
      SuspensionEstimateMeta self, SseSerializer serializer);

  @protected
  void sse_encode_table_model(TableModel self, SseSerializer serializer);

  @protected
  void sse_encode_track_arg(TrackArg self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_failure(VideoFailure self, SseSerializer serializer);

  @protected
  void sse_encode_video_failure_kind(
      VideoFailureKind self, SseSerializer serializer);

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer);

  @protected
  void sse_encode_video_sync_method(
      VideoSyncMethod self, SseSerializer serializer);

  @protected
  void sse_encode_video_sync_outcome(
      VideoSyncOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_visit_window(VisitWindow self, SseSerializer serializer);

  @protected
  void sse_encode_welch_result(WelchResult self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void rust_arc_increment_strong_count_RustOpaque_SessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_SessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_SessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_idl0_rust_arc_increment_strong_count_RustOpaque_SessionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_SessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_SessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_SessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_SessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_SessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_idl0_rust_arc_decrement_strong_count_RustOpaque_SessionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_SessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_SessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_idl0_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_idl0_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSessionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
