// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mirror of [`idl_rs::histogram::HistogramResult`] for FRB codegen.
class HistogramResult {
  final Float64List binEdges;
  final Uint32List counts;
  final int total;

  const HistogramResult({
    required this.binEdges,
    required this.counts,
    required this.total,
  });

  @override
  int get hashCode => binEdges.hashCode ^ counts.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistogramResult &&
          runtimeType == other.runtimeType &&
          binEdges == other.binEdges &&
          counts == other.counts &&
          total == other.total;
}
