// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_core`, `into_core`

/// Detect laps for the retained session handle. `window_start_ms` +
/// `window_end_ms` form an inclusive visit window when both are `Some`
/// (otherwise the whole session is used).
Future<List<Lap>> detectLaps(
        {required SessionHandle handle,
        required LapTimingArg timing,
        required List<SectorGateArg> sectorGates,
        required List<NeutralZoneArg> neutralZones,
        PlatformInt64? windowStartMs,
        PlatformInt64? windowEndMs}) =>
    RustLib.instance.api.crateLapsDetectLaps(
        handle: handle,
        timing: timing,
        sectorGates: sectorGates,
        neutralZones: neutralZones,
        windowStartMs: windowStartMs,
        windowEndMs: windowEndMs);

/// FFI gate (four raw-scale coordinates, degrees × 1e7).
class GateArg {
  final double lat1;
  final double lon1;
  final double lat2;
  final double lon2;

  const GateArg({
    required this.lat1,
    required this.lon1,
    required this.lat2,
    required this.lon2,
  });

  @override
  int get hashCode =>
      lat1.hashCode ^ lon1.hashCode ^ lat2.hashCode ^ lon2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GateArg &&
          runtimeType == other.runtimeType &&
          lat1 == other.lat1 &&
          lon1 == other.lon1 &&
          lat2 == other.lat2 &&
          lon2 == other.lon2;
}

class Lap {
  final int lapNumber;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final double startTimeSecs;
  final double endTimeSecs;
  final PlatformInt64 rawElapsedMs;
  final PlatformInt64 lapTimeMs;
  final List<Sector> sectors;
  final List<NeutralZoneVisit> neutralZoneVisits;

  const Lap({
    required this.lapNumber,
    required this.startMs,
    required this.endMs,
    required this.startTimeSecs,
    required this.endTimeSecs,
    required this.rawElapsedMs,
    required this.lapTimeMs,
    required this.sectors,
    required this.neutralZoneVisits,
  });

  @override
  int get hashCode =>
      lapNumber.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      startTimeSecs.hashCode ^
      endTimeSecs.hashCode ^
      rawElapsedMs.hashCode ^
      lapTimeMs.hashCode ^
      sectors.hashCode ^
      neutralZoneVisits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lap &&
          runtimeType == other.runtimeType &&
          lapNumber == other.lapNumber &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          startTimeSecs == other.startTimeSecs &&
          endTimeSecs == other.endTimeSecs &&
          rawElapsedMs == other.rawElapsedMs &&
          lapTimeMs == other.lapTimeMs &&
          sectors == other.sectors &&
          neutralZoneVisits == other.neutralZoneVisits;
}

/// Freezed-free lap-timing config. `Circuit` reads `start` only (`finish`
/// mirrors it); `PointToPoint` reads both.
class LapTimingArg {
  final LapTimingKind kind;
  final GateArg start;
  final GateArg finish;

  const LapTimingArg({
    required this.kind,
    required this.start,
    required this.finish,
  });

  @override
  int get hashCode => kind.hashCode ^ start.hashCode ^ finish.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LapTimingArg &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          start == other.start &&
          finish == other.finish;
}

/// Discriminant for [`LapTimingArg`].
enum LapTimingKind {
  circuit,
  pointToPoint,
  ;
}

class NeutralZoneArg {
  final String name;
  final GateArg enter;
  final GateArg exit;

  const NeutralZoneArg({
    required this.name,
    required this.enter,
    required this.exit,
  });

  @override
  int get hashCode => name.hashCode ^ enter.hashCode ^ exit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeutralZoneArg &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          enter == other.enter &&
          exit == other.exit;
}

class NeutralZoneVisit {
  final String name;
  final PlatformInt64 enterMs;
  final PlatformInt64 exitMs;

  const NeutralZoneVisit({
    required this.name,
    required this.enterMs,
    required this.exitMs,
  });

  @override
  int get hashCode => name.hashCode ^ enterMs.hashCode ^ exitMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NeutralZoneVisit &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          enterMs == other.enterMs &&
          exitMs == other.exitMs;
}

class Sector {
  final String name;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final double startTimeSecs;
  final double endTimeSecs;

  const Sector({
    required this.name,
    required this.startMs,
    required this.endMs,
    required this.startTimeSecs,
    required this.endTimeSecs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      startTimeSecs.hashCode ^
      endTimeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Sector &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          startTimeSecs == other.startTimeSecs &&
          endTimeSecs == other.endTimeSecs;
}

class SectorGateArg {
  final String name;
  final GateArg gate;

  const SectorGateArg({
    required this.name,
    required this.gate,
  });

  @override
  int get hashCode => name.hashCode ^ gate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SectorGateArg &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          gate == other.gate;
}
