// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `into_core`, `zip_bounds`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SharedHandleLookup`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `best_time_base_dims`, `from`, `lookup`

/// Evaluate `expression` against the retained session handle + lap context and
/// upsert the result into the handle's math store under `store_as`. Only
/// metadata crosses FFI — at 100M samples the old full-vector return cost
/// ~800 MB serialized each way per eval (spec §15 seam).
Future<EvalStoredMeta> evalMathIntoStore(
        {required SessionHandle handle,
        required String expression,
        required String storeAs,
        required MathLapCtxArg lapCtx}) =>
    RustLib.instance.api.crateMathEvalMathIntoStore(
        handle: handle,
        expression: expression,
        storeAs: storeAs,
        lapCtx: lapCtx);

/// Resolve the transitive math-channel dependencies of `target_expression` into
/// `handle`'s math store, so the caller's subsequent `eval_math` reads them
/// Rust-side. `defs` is the full math-channel set; `target_name` seeds the cycle
/// guard. Replaces the former Dart `_resolveDependenciesIntoHandle`.
Future<void> resolveMathDependencies(
        {required SessionHandle handle,
        required String targetName,
        required String targetExpression,
        required List<MathChannelDefArg> defs,
        required MathLapCtxArg lapCtx}) =>
    RustLib.instance.api.crateMathResolveMathDependencies(
        handle: handle,
        targetName: targetName,
        targetExpression: targetExpression,
        defs: defs,
        lapCtx: lapCtx);

/// Metadata of a stored eval result — the samples stay in the handle's math
/// store; Dart reads them only as decimated tiles / bounded views.
class EvalStoredMeta {
  /// Number of samples in the stored result.
  final int length;

  /// Output sample rate in Hz (0.0 = scalar-as-channel).
  final double sampleRateHz;

  const EvalStoredMeta({
    required this.length,
    required this.sampleRateHz,
  });

  @override
  int get hashCode => length.hashCode ^ sampleRateHz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvalStoredMeta &&
          runtimeType == other.runtimeType &&
          length == other.length &&
          sampleRateHz == other.sampleRateHz;
}

/// FFI-friendly math-channel definition — the engine needs only name +
/// expression (the output rate is derived at eval time). See spec §8.1.
class MathChannelDefArg {
  final String name;
  final String expression;

  const MathChannelDefArg({
    required this.name,
    required this.expression,
  });

  @override
  int get hashCode => name.hashCode ^ expression.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathChannelDefArg &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          expression == other.expression;
}

/// Error returned by [`eval_math`].
class MathEvalFailure implements FrbException {
  final MathEvalFailureKind kind;
  final String message;

  const MathEvalFailure({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathEvalFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Discriminant for [`MathEvalFailure`]. Unit enum → plain Dart enum.
enum MathEvalFailureKind {
  parse,
  unknownFunction,
  unknownChannel,
  argCount,
  type,
  divisionByZero,
  noLapContext,
  notImplemented,
  runtime,
  ;
}

/// FFI-friendly mirror of the core `MathLapContext`. Lap/sector bounds cross as
/// parallel arrays (FRB cannot bridge `Vec<(f64,f64)>`).
class MathLapCtxArg {
  final Float64List mainLapStarts;
  final Float64List mainLapEnds;
  final Float64List mainSectorStarts;
  final Float64List mainSectorEnds;
  final int? mainLapNumber;
  final MathOverlayArg? overlay;

  const MathLapCtxArg({
    required this.mainLapStarts,
    required this.mainLapEnds,
    required this.mainSectorStarts,
    required this.mainSectorEnds,
    this.mainLapNumber,
    this.overlay,
  });

  @override
  int get hashCode =>
      mainLapStarts.hashCode ^
      mainLapEnds.hashCode ^
      mainSectorStarts.hashCode ^
      mainSectorEnds.hashCode ^
      mainLapNumber.hashCode ^
      overlay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathLapCtxArg &&
          runtimeType == other.runtimeType &&
          mainLapStarts == other.mainLapStarts &&
          mainLapEnds == other.mainLapEnds &&
          mainSectorStarts == other.mainSectorStarts &&
          mainSectorEnds == other.mainSectorEnds &&
          mainLapNumber == other.mainLapNumber &&
          overlay == other.overlay;
}

/// Overlay designation for `variance_*`. The overlay session crosses as a
/// second handle; its lap window crosses as scalars.
class MathOverlayArg {
  final SessionHandle handle;
  final double lapStartMs;
  final double lapEndMs;
  final double lapStartUniformSec;

  const MathOverlayArg({
    required this.handle,
    required this.lapStartMs,
    required this.lapEndMs,
    required this.lapStartUniformSec,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      lapStartMs.hashCode ^
      lapEndMs.hashCode ^
      lapStartUniformSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathOverlayArg &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          lapStartMs == other.lapStartMs &&
          lapEndMs == other.lapEndMs &&
          lapStartUniformSec == other.lapStartUniformSec;
}
