// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Paired, finite, decimated `(x, y)` cloud over `[t0, t1]` capped at
/// `max_points`, with optional per-point colour and the pre-decimation extent.
Future<ScatterPoints> scatterPoints(
        {required SessionHandle handle,
        required String xChannel,
        required String yChannel,
        String? colorChannel,
        required double t0Secs,
        required double t1Secs,
        required int maxPoints}) =>
    RustLib.instance.api.crateScatterScatterPoints(
        handle: handle,
        xChannel: xChannel,
        yChannel: yChannel,
        colorChannel: colorChannel,
        t0Secs: t0Secs,
        t1Secs: t1Secs,
        maxPoints: maxPoints);

/// 2D count histogram of the `(x, y)` cloud over `[t0, t1]`; `equal_aspect`
/// squares the range for the G-G friction circle. Bounds come back in the result.
Future<ScatterDensity> scatterDensity(
        {required SessionHandle handle,
        required String xChannel,
        required String yChannel,
        required double t0Secs,
        required double t1Secs,
        required int bins,
        required bool equalAspect}) =>
    RustLib.instance.api.crateScatterScatterDensity(
        handle: handle,
        xChannel: xChannel,
        yChannel: yChannel,
        t0Secs: t0Secs,
        t1Secs: t1Secs,
        bins: bins,
        equalAspect: equalAspect);

class ScatterDensity {
  final int bins;
  final double xMin;
  final double xMax;
  final double yMin;
  final double yMax;
  final Uint32List counts;

  const ScatterDensity({
    required this.bins,
    required this.xMin,
    required this.xMax,
    required this.yMin,
    required this.yMax,
    required this.counts,
  });

  @override
  int get hashCode =>
      bins.hashCode ^
      xMin.hashCode ^
      xMax.hashCode ^
      yMin.hashCode ^
      yMax.hashCode ^
      counts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScatterDensity &&
          runtimeType == other.runtimeType &&
          bins == other.bins &&
          xMin == other.xMin &&
          xMax == other.xMax &&
          yMin == other.yMin &&
          yMax == other.yMax &&
          counts == other.counts;
}

class ScatterPoints {
  final Float64List xs;
  final Float64List ys;
  final Float64List? colors;
  final double xMin;
  final double xMax;
  final double yMin;
  final double yMax;

  const ScatterPoints({
    required this.xs,
    required this.ys,
    this.colors,
    required this.xMin,
    required this.xMax,
    required this.yMin,
    required this.yMax,
  });

  @override
  int get hashCode =>
      xs.hashCode ^
      ys.hashCode ^
      colors.hashCode ^
      xMin.hashCode ^
      xMax.hashCode ^
      yMin.hashCode ^
      yMax.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScatterPoints &&
          runtimeType == other.runtimeType &&
          xs == other.xs &&
          ys == other.ys &&
          colors == other.colors &&
          xMin == other.xMin &&
          xMax == other.xMax &&
          yMin == other.yMin &&
          yMax == other.yMax;
}
