// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'fft.dart';
import 'frb_generated.dart';
import 'histogram.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'spectrogram.dart';
import 'table.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// Parse `.idl0` bytes into an owned session handle.
Future<SessionHandle> parseSession({required List<int> bytes}) =>
    RustLib.instance.api.crateSessionParseSession(bytes: bytes);

/// Read + parse an `.idl0` file path (Rust does the IO; no big buffer crosses FFI).
Future<SessionHandle> parseSessionFromPath({required String path}) =>
    RustLib.instance.api.crateSessionParseSessionFromPath(path: path);

/// Build a handle from caller-parsed channels (GPX path).
Future<SessionHandle> sessionFromChannels(
        {required SessionMetaInput meta,
        required List<ChannelInput> channels}) =>
    RustLib.instance.api
        .crateSessionSessionFromChannels(meta: meta, channels: channels);

Future<SessionMeta> sessionMetadata({required SessionHandle handle}) =>
    RustLib.instance.api.crateSessionSessionMetadata(handle: handle);

Future<List<ChannelMeta>> sessionChannels({required SessionHandle handle}) =>
    RustLib.instance.api.crateSessionSessionChannels(handle: handle);

/// Resident sample-storage bytes for the handle — the input to the app's
/// byte-budgeted residency policy (§15.3).
Future<BigInt> sessionResidentBytes({required SessionHandle handle}) =>
    RustLib.instance.api.crateSessionSessionResidentBytes(handle: handle);

Future<Float64List> channelSamples(
        {required SessionHandle handle, required String channelId}) =>
    RustLib.instance.api
        .crateSessionChannelSamples(handle: handle, channelId: channelId);

Future<Float64List?> channelSampleTimes(
        {required SessionHandle handle, required String channelId}) =>
    RustLib.instance.api
        .crateSessionChannelSampleTimes(handle: handle, channelId: channelId);

/// Encode the session as a Garmin FIT activity (for Strava) and return the
/// bytes. `laps` is empty for a single whole-ride lap, or one entry per detected
/// lap (Strava renders them as splits). Heart rate + GPS are read from the
/// handle. Returns an error string on failure (only `NoGpsData` in practice —
/// the app gates export on GPS presence). Lives here so it shares the canonical
/// opaque `SessionHandle` type.
Future<Uint8List> exportFitToVec(
        {required SessionHandle handle,
        required FitSport sport,
        required List<FitLap> laps}) =>
    RustLib.instance.api
        .crateSessionExportFitToVec(handle: handle, sport: sport, laps: laps);

/// Finite Y-axis bounds for `channel_id`; `None` when absent or all-non-finite.
Future<ChannelBounds?> channelMinMax(
        {required SessionHandle handle, required String channelId}) =>
    RustLib.instance.api
        .crateSessionChannelMinMax(handle: handle, channelId: channelId);

/// Physical samples for the half-open index window `[start, end)`; clamped to the
/// channel length, empty for an absent channel or empty window.
Future<Float64List> materializeF64(
        {required SessionHandle handle,
        required String channelId,
        required int start,
        required int end}) =>
    RustLib.instance.api.crateSessionMaterializeF64(
        handle: handle, channelId: channelId, start: start, end: end);

/// Slice `channel_id` to `[t0_secs, t1_secs]`, sample-0-rebase it, and upsert it
/// into the handle's derived store under a typed lap-slice key. `overlay` picks
/// the role (overlay vs main lap); `lap` is the lap number. Returns the storage
/// token + length; the slice never crosses FFI (spec §15.3 seam).
Future<SliceLapResult> sliceLapIntoStore(
        {required SessionHandle handle,
        required String channelId,
        required bool overlay,
        required int lap,
        required double t0Secs,
        required double t1Secs}) =>
    RustLib.instance.api.crateSessionSliceLapIntoStore(
        handle: handle,
        channelId: channelId,
        overlay: overlay,
        lap: lap,
        t0Secs: t0Secs,
        t1Secs: t1Secs);

/// Reclaim derived entries not backed by reality: keeps math outputs whose name
/// is in `live_sources` and lap slices whose source is live or a base channel,
/// dropping the rest (a deleted/renamed math channel's output + slices). Called
/// on the eval path with the current channel-name list (spec §4).
Future<void> retainDerived(
        {required SessionHandle handle, required List<String> liveSources}) =>
    RustLib.instance.api
        .crateSessionRetainDerived(handle: handle, liveSources: liveSources);

/// Welch spectrum for `channel_id`, computed in the engine straight from the
/// retained handle ([`SessionHandle::welch_channel`]) — the channel's samples
/// never cross FFI, only the `WelchResult` does (Phase D-drain). Empty result for
/// an absent channel. Lives here, beside the other handle accessors, so it shares
/// the canonical `SessionHandle` opaque type (the FFT `WelchResult`/window enums
/// are mirrored in `crate::fft`).
Future<WelchResult> welchChannel(
        {required SessionHandle handle,
        required String channelId,
        required FftWindow window,
        required BigInt nperseg,
        required BigInt noverlap,
        required Detrend detrend,
        required Averaging averaging,
        required Scaling scaling}) =>
    RustLib.instance.api.crateSessionWelchChannel(
        handle: handle,
        channelId: channelId,
        window: window,
        nperseg: nperseg,
        noverlap: noverlap,
        detrend: detrend,
        averaging: averaging,
        scaling: scaling);

/// Windowed Welch spectrum for `channel_id` over `[t0_secs, t1_secs]`, computed
/// in the engine ([`SessionHandle::welch_channel_windowed`]) — only the
/// `WelchResult` crosses FFI. Lives here beside `welch_channel` so it shares the
/// canonical opaque `SessionHandle` type.
Future<WelchResult> welchChannelWindowed(
        {required SessionHandle handle,
        required String channelId,
        required double t0Secs,
        required double t1Secs,
        required FftWindow window,
        required BigInt nperseg,
        required BigInt noverlap,
        required Detrend detrend,
        required Averaging averaging,
        required Scaling scaling}) =>
    RustLib.instance.api.crateSessionWelchChannelWindowed(
        handle: handle,
        channelId: channelId,
        t0Secs: t0Secs,
        t1Secs: t1Secs,
        window: window,
        nperseg: nperseg,
        noverlap: noverlap,
        detrend: detrend,
        averaging: averaging,
        scaling: scaling);

/// Spectrogram for `channel_id` over `[t0_secs, t1_secs]`, computed in the engine
/// ([`SessionHandle::spectrogram_channel`]) — only the flat
/// [`SpectrogramResult`](crate::spectrogram::SpectrogramResult) crosses FFI.
/// `times_secs` in the result are absolute session seconds. Lives here beside the
/// other handle accessors so it shares the canonical `SessionHandle` opaque type
/// (the `SpectrogramResult` mirror is in `crate::spectrogram`).
Future<SpectrogramResult> spectrogramChannel(
        {required SessionHandle handle,
        required String channelId,
        required double t0Secs,
        required double t1Secs,
        required FftWindow window,
        required BigInt nperseg,
        required BigInt noverlap,
        required Detrend detrend,
        required Scaling scaling}) =>
    RustLib.instance.api.crateSessionSpectrogramChannel(
        handle: handle,
        channelId: channelId,
        t0Secs: t0Secs,
        t1Secs: t1Secs,
        window: window,
        nperseg: nperseg,
        noverlap: noverlap,
        detrend: detrend,
        scaling: scaling);

/// Value-distribution histogram for `channel_id`, computed in the engine from
/// the retained handle ([`SessionHandle::histogram`]) — the channel's samples
/// never cross FFI, only the `HistogramResult` does. `bin_count` equal-width
/// bins; `symmetric` centres the range on zero (signed velocity distributions).
/// Empty result for an absent channel. Lives here beside the other handle
/// accessors so it shares the canonical `SessionHandle` opaque type (the
/// `HistogramResult` mirror is in `crate::histogram`).
Future<HistogramResult> channelHistogram(
        {required SessionHandle handle,
        required String channelId,
        required int binCount,
        required bool symmetric,
        double? rangeMin,
        double? rangeMax}) =>
    RustLib.instance.api.crateSessionChannelHistogram(
        handle: handle,
        channelId: channelId,
        binCount: binCount,
        symmetric: symmetric,
        rangeMin: rangeMin,
        rangeMax: rangeMax);

/// Evaluate a table against the session handle. `row_windows[r]` is row `r`'s
/// `(t0_secs, t1_secs)` and `row_has_window[r]` whether that window applies
/// (FRB has no `Option<(f64,f64)>` across a `Vec`, so the window is split into a
/// value vec + a presence vec). Only the small per-cell results cross FFI. Lives
/// here (not table.rs) so it shares the opaque `SessionHandle` type.
Future<List<List<CellResult>>> evaluateTable(
        {required SessionHandle handle,
        required TableModel table,
        required List<(double, double)> rowWindows,
        required List<bool> rowHasWindow}) =>
    RustLib.instance.api.crateSessionEvaluateTable(
        handle: handle,
        table: table,
        rowWindows: rowWindows,
        rowHasWindow: rowHasWindow);

/// Multi-session table evaluation. `handles` is the distinct session pool;
/// `row_handle_idx[r]` selects row `r`'s handle. `baseline_row` (when present)
/// is the row `main({col[]})` reads from. See `idl_rs::table::evaluate_table_multi`.
Future<List<List<CellResult>>> evaluateTableMulti(
        {required List<SessionHandle> handles,
        required List<int> rowHandleIdx,
        required TableModel table,
        required List<(double, double)> rowWindows,
        required List<bool> rowHasWindow,
        int? baselineRow}) =>
    RustLib.instance.api.crateSessionEvaluateTableMulti(
        handles: handles,
        rowHandleIdx: rowHandleIdx,
        table: table,
        rowWindows: rowWindows,
        rowHasWindow: rowHasWindow,
        baselineRow: baselineRow);

/// Batch variance: each target lap vs one reference lap, in time (mode 0) or
/// distance (mode 1). Target lap fields are parallel arrays (FRB has no
/// `Vec<struct-with-opaque>`); each target's handle is in `target_handles`.
/// Returns one delta series per target, in order. See
/// `idl_rs::variance::variance_traces`.
Future<List<Float64List>> varianceTraces(
        {required SessionHandle reference,
        required double referenceLapStartMs,
        required double referenceLapEndMs,
        required double referenceLapStartUniformSec,
        required List<SessionHandle> targetHandles,
        required List<double> targetLapStartMs,
        required List<double> targetLapEndMs,
        required List<double> targetLapStartUniformSec,
        required List<double> targetWindowStartSec,
        required List<double> targetWindowEndSec,
        required String channelId,
        required int mode}) =>
    RustLib.instance.api.crateSessionVarianceTraces(
        reference: reference,
        referenceLapStartMs: referenceLapStartMs,
        referenceLapEndMs: referenceLapEndMs,
        referenceLapStartUniformSec: referenceLapStartUniformSec,
        targetHandles: targetHandles,
        targetLapStartMs: targetLapStartMs,
        targetLapEndMs: targetLapEndMs,
        targetLapStartUniformSec: targetLapStartUniformSec,
        targetWindowStartSec: targetWindowStartSec,
        targetWindowEndSec: targetWindowEndSec,
        channelId: channelId,
        mode: mode);

/// Default filter tuning (the engine's reference defaults) — the app's starting
/// point for live tuning. See [`SuspensionConfig`].
Future<SuspensionConfig> suspensionConfigDefault() =>
    RustLib.instance.api.crateSessionSuspensionConfigDefault();

/// Run the offline suspension-kinematics estimator over the retained session handle
/// and store its per-sample outputs into the handle's math store: front (and, with
/// rear suspension, rear) **wheel travel in mm** and **wheel velocity in mm/s**.
/// Only metadata crosses FFI — the chart decimates the stored channels by id (spec
/// §15.3 seam), exactly like `eval_math_into_store`. Geometry is the engine
/// reference bike, carrying flat-ground-calibrated unsprung mounts (per-session
/// tilt refitting is the opt-in `refine_mounts`); `config` carries the live-tunable
/// filter parameters, including GPS-velocity aiding (latency, min-speed gate) and
/// the RTS wheel smoother (`smooth`, default on). Errors only when the session has
/// no IMU0 channels.
Future<SuspensionEstimateMeta> estimateSuspensionIntoStore(
        {required SessionHandle handle, required SuspensionConfig config}) =>
    RustLib.instance.api.crateSessionEstimateSuspensionIntoStore(
        handle: handle, config: config);

/// Finite (min, max) bounds for a channel — FFI shape for
/// [`SessionHandle::channel_min_max`]. Plain struct (no freezed).
class ChannelBounds {
  final double min;
  final double max;

  const ChannelBounds({
    required this.min,
    required this.max,
  });

  @override
  int get hashCode => min.hashCode ^ max.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelBounds &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max;
}

class ChannelInput {
  final String channelId;
  final double sampleRateHz;
  final Float64List samples;
  final Float64List? sampleTimesSecs;

  const ChannelInput({
    required this.channelId,
    required this.sampleRateHz,
    required this.samples,
    this.sampleTimesSecs,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      sampleRateHz.hashCode ^
      samples.hashCode ^
      sampleTimesSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelInput &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          sampleRateHz == other.sampleRateHz &&
          samples == other.samples &&
          sampleTimesSecs == other.sampleTimesSecs;
}

class ChannelMeta {
  final String channelId;
  final double sampleRateHz;
  final int length;
  final bool isEventDriven;
  final bool synthesized;

  const ChannelMeta({
    required this.channelId,
    required this.sampleRateHz,
    required this.length,
    required this.isEventDriven,
    required this.synthesized,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      sampleRateHz.hashCode ^
      length.hashCode ^
      isEventDriven.hashCode ^
      synthesized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelMeta &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          sampleRateHz == other.sampleRateHz &&
          length == other.length &&
          isEventDriven == other.isEventDriven &&
          synthesized == other.synthesized;
}

/// One lap's timing for FIT export (mirrors `idl_rs::export::FitLap`). All
/// fields are milliseconds.
class FitLap {
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final PlatformInt64 elapsedMs;

  const FitLap({
    required this.startMs,
    required this.endMs,
    required this.elapsedMs,
  });

  @override
  int get hashCode => startMs.hashCode ^ endMs.hashCode ^ elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FitLap &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          elapsedMs == other.elapsedMs;
}

/// FIT sport classification (mirrors `idl_rs::export::FitSport`). Unit enum →
/// plain Dart enum (no freezed).
enum FitSport {
  generic,
  running,
  cycling,
  motorcycling,
  ;
}

/// Discriminant for [`ParseFailure`]. A unit enum → a plain Dart enum (no freezed).
enum ParseErrorKind {
  invalidMagicBytes,
  unsupportedSchemaVersion,
  truncatedRecord,
  io,
  ;
}

/// Error returned by the `parse_session*` entry points.
class ParseFailure implements FrbException {
  final ParseErrorKind kind;
  final String message;

  const ParseFailure({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

class SessionMeta {
  final String sessionId;
  final String deviceId;
  final PlatformInt64 timestampUtcMs;
  final String configChecksum;
  final int channelCount;
  final PlatformInt64 durationMs;
  final String? truncationWarning;

  const SessionMeta({
    required this.sessionId,
    required this.deviceId,
    required this.timestampUtcMs,
    required this.configChecksum,
    required this.channelCount,
    required this.durationMs,
    this.truncationWarning,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      deviceId.hashCode ^
      timestampUtcMs.hashCode ^
      configChecksum.hashCode ^
      channelCount.hashCode ^
      durationMs.hashCode ^
      truncationWarning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionMeta &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          deviceId == other.deviceId &&
          timestampUtcMs == other.timestampUtcMs &&
          configChecksum == other.configChecksum &&
          channelCount == other.channelCount &&
          durationMs == other.durationMs &&
          truncationWarning == other.truncationWarning;
}

class SessionMetaInput {
  final String sessionId;
  final String deviceId;
  final PlatformInt64 timestampUtcMs;
  final String configChecksum;

  const SessionMetaInput({
    required this.sessionId,
    required this.deviceId,
    required this.timestampUtcMs,
    required this.configChecksum,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      deviceId.hashCode ^
      timestampUtcMs.hashCode ^
      configChecksum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionMetaInput &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          deviceId == other.deviceId &&
          timestampUtcMs == other.timestampUtcMs &&
          configChecksum == other.configChecksum;
}

/// Result of [`slice_lap_into_store`]: the opaque storage token the chart
/// decimates by, plus the slice length (0 = no sample in window, nothing stored).
class SliceLapResult {
  final String token;
  final int length;

  const SliceLapResult({
    required this.token,
    required this.length,
  });

  @override
  int get hashCode => token.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SliceLapResult &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          length == other.length;
}

/// Flat, FFI-friendly mirror of the engine's `EstimatorConfig` — the full filter
/// tuning surface the app exposes for live (hot-reload) tuning. Start from
/// [`suspension_config_default`] and override fields.
class SuspensionConfig {
  /// Estimate steering states (M2a: false — wheels first).
  final bool estimateSteering;

  /// Measurement-update iterations (1 = plain EKF).
  final int iekfIters;

  /// Stationary-detector window, samples.
  final int zuptWindow;

  /// Stationary accel-magnitude std threshold, m/s².
  final double zuptAccelStd;

  /// Stationary mean gyro-magnitude threshold, rad/s.
  final double zuptGyroThresh;

  /// ZUPT velocity pseudo-measurement std, m/s.
  final double zuptSigma;

  /// ZARU bias pseudo-measurement std, rad/s.
  final double zaruSigma;

  /// Gravity-leveling tilt residual std.
  final double gravitySigma;

  /// GPS velocity std, m/s.
  final double gpsSigma;

  /// Sag-prior std, m (deliberately loose — a weak anti-drift tether).
  final double sagSigma;

  /// Travel-barrier std, m (smaller ⇒ stiffer `[0, max]` wall).
  final double barrierSigma;

  /// IMU0 specific-force magnitude below which a sample is airborne, m/s².
  final double airborneAccelThresh;

  /// Max lever-compensated diff-accel magnitude (per unsprung IMU) for a sample to
  /// still count as airborne, m/s² — the relative free-fall veto. A grounded but
  /// terrain-driven wheel has a large diff-accel even when the chassis is light, so
  /// requiring it small stops rough ground from snapping travel to topout. Larger ⇒
  /// looser; smaller ⇒ stricter.
  final double airborneDiffThresh;

  /// Topout-reference std applied on airborne samples (the travel-DC anchor), m.
  final double topoutSigma;

  /// GPS output latency, s — a fix logged at `t` describes the bike at
  /// `t − latency` (the module's internal filter delays its solution). Tune
  /// against hard-braking events.
  final double gpsLatencyS;

  /// Minimum GPS horizontal speed for a fix to be used, m/s (course is noise
  /// below walking pace; ZUPT covers stationary).
  final double gpsMinSpeedMps;

  /// Re-fit the unsprung mounts' tilt against this session's first stationary
  /// window (default false — the geometry carries flat-ground-calibrated mounts;
  /// a ride's parked lean / flopped bars would be absorbed as mount error).
  final bool refineMounts;

  /// Run the RTS backward pass over the wheel travel/velocity chains (default
  /// true) — distributes each topout/stop anchor over the interval before it
  /// instead of correcting only forward. `false` = raw causal filter.
  final bool smooth;

  /// IMU0 gyro angle random walk, rad/√s.
  final double gyroArw;

  /// IMU0 accel velocity random walk, (m/s)/√s.
  final double accelVrw;

  /// IMU0 gyro-bias random walk, (rad/s)/√s.
  final double gyroBiasRw;

  /// IMU0 accel-bias random walk, (m/s²)/√s.
  final double accelBiasRw;

  /// IMU1 (front-unsprung) gyro-bias random walk, (rad/s)/√s.
  final double gyro1BiasRw;

  /// IMU2 (rear-unsprung) gyro-bias random walk, (rad/s)/√s.
  final double gyro2BiasRw;

  /// Wheel-velocity driving noise, (m/s²)/√s.
  final double wheelVelRw;

  /// Wheel-travel regularizing noise, (m)/√s.
  final double wheelPosRw;

  /// Steer-rate driving noise, (rad/s²)/√s.
  final double steerRateRw;

  /// Initial attitude-tilt 1-σ prior, rad.
  final double initAttitude;

  /// Initial velocity 1-σ prior, m/s.
  final double initVelocity;

  /// Initial gyro-bias 1-σ prior, rad/s.
  final double initGyroBias;

  /// Initial accel-bias 1-σ prior, m/s².
  final double initAccelBias;

  /// Initial wheel-travel 1-σ prior, m.
  final double initWheelTravel;

  /// Initial wheel-velocity 1-σ prior, m/s.
  final double initWheelVelocity;

  /// Initial steer-angle 1-σ prior, rad.
  final double initSteerAngle;

  /// Initial steer-rate 1-σ prior, rad/s.
  final double initSteerRate;

  const SuspensionConfig({
    required this.estimateSteering,
    required this.iekfIters,
    required this.zuptWindow,
    required this.zuptAccelStd,
    required this.zuptGyroThresh,
    required this.zuptSigma,
    required this.zaruSigma,
    required this.gravitySigma,
    required this.gpsSigma,
    required this.sagSigma,
    required this.barrierSigma,
    required this.airborneAccelThresh,
    required this.airborneDiffThresh,
    required this.topoutSigma,
    required this.gpsLatencyS,
    required this.gpsMinSpeedMps,
    required this.refineMounts,
    required this.smooth,
    required this.gyroArw,
    required this.accelVrw,
    required this.gyroBiasRw,
    required this.accelBiasRw,
    required this.gyro1BiasRw,
    required this.gyro2BiasRw,
    required this.wheelVelRw,
    required this.wheelPosRw,
    required this.steerRateRw,
    required this.initAttitude,
    required this.initVelocity,
    required this.initGyroBias,
    required this.initAccelBias,
    required this.initWheelTravel,
    required this.initWheelVelocity,
    required this.initSteerAngle,
    required this.initSteerRate,
  });

  @override
  int get hashCode =>
      estimateSteering.hashCode ^
      iekfIters.hashCode ^
      zuptWindow.hashCode ^
      zuptAccelStd.hashCode ^
      zuptGyroThresh.hashCode ^
      zuptSigma.hashCode ^
      zaruSigma.hashCode ^
      gravitySigma.hashCode ^
      gpsSigma.hashCode ^
      sagSigma.hashCode ^
      barrierSigma.hashCode ^
      airborneAccelThresh.hashCode ^
      airborneDiffThresh.hashCode ^
      topoutSigma.hashCode ^
      gpsLatencyS.hashCode ^
      gpsMinSpeedMps.hashCode ^
      refineMounts.hashCode ^
      smooth.hashCode ^
      gyroArw.hashCode ^
      accelVrw.hashCode ^
      gyroBiasRw.hashCode ^
      accelBiasRw.hashCode ^
      gyro1BiasRw.hashCode ^
      gyro2BiasRw.hashCode ^
      wheelVelRw.hashCode ^
      wheelPosRw.hashCode ^
      steerRateRw.hashCode ^
      initAttitude.hashCode ^
      initVelocity.hashCode ^
      initGyroBias.hashCode ^
      initAccelBias.hashCode ^
      initWheelTravel.hashCode ^
      initWheelVelocity.hashCode ^
      initSteerAngle.hashCode ^
      initSteerRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuspensionConfig &&
          runtimeType == other.runtimeType &&
          estimateSteering == other.estimateSteering &&
          iekfIters == other.iekfIters &&
          zuptWindow == other.zuptWindow &&
          zuptAccelStd == other.zuptAccelStd &&
          zuptGyroThresh == other.zuptGyroThresh &&
          zuptSigma == other.zuptSigma &&
          zaruSigma == other.zaruSigma &&
          gravitySigma == other.gravitySigma &&
          gpsSigma == other.gpsSigma &&
          sagSigma == other.sagSigma &&
          barrierSigma == other.barrierSigma &&
          airborneAccelThresh == other.airborneAccelThresh &&
          airborneDiffThresh == other.airborneDiffThresh &&
          topoutSigma == other.topoutSigma &&
          gpsLatencyS == other.gpsLatencyS &&
          gpsMinSpeedMps == other.gpsMinSpeedMps &&
          refineMounts == other.refineMounts &&
          smooth == other.smooth &&
          gyroArw == other.gyroArw &&
          accelVrw == other.accelVrw &&
          gyroBiasRw == other.gyroBiasRw &&
          accelBiasRw == other.accelBiasRw &&
          gyro1BiasRw == other.gyro1BiasRw &&
          gyro2BiasRw == other.gyro2BiasRw &&
          wheelVelRw == other.wheelVelRw &&
          wheelPosRw == other.wheelPosRw &&
          steerRateRw == other.steerRateRw &&
          initAttitude == other.initAttitude &&
          initVelocity == other.initVelocity &&
          initGyroBias == other.initGyroBias &&
          initAccelBias == other.initAccelBias &&
          initWheelTravel == other.initWheelTravel &&
          initWheelVelocity == other.initWheelVelocity &&
          initSteerAngle == other.initSteerAngle &&
          initSteerRate == other.initSteerRate;
}

/// Failure from [`estimate_suspension_into_store`].
class SuspensionEstimateFailure implements FrbException {
  final String message;

  const SuspensionEstimateFailure({
    required this.message,
  });

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuspensionEstimateFailure &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Metadata of a stored suspension-estimator run. The per-sample outputs stay in
/// the handle's math store under `channel_ids`; the chart reads them by id.
class SuspensionEstimateMeta {
  /// Ids of the channels stored this run (front/rear travel + velocity).
  final List<String> channelIds;

  /// Number of samples per output channel.
  final int length;

  /// Output sample rate, Hz (= IMU0 rate).
  final double sampleRateHz;

  /// Front dynamic sag — median front travel over riding samples, mm (None if
  /// never riding). An emergent output, not an input (see the engine doc).
  final double? frontDynamicSagMm;

  /// Rear dynamic sag, mm (None if never riding or no rear suspension).
  final double? rearDynamicSagMm;

  const SuspensionEstimateMeta({
    required this.channelIds,
    required this.length,
    required this.sampleRateHz,
    this.frontDynamicSagMm,
    this.rearDynamicSagMm,
  });

  @override
  int get hashCode =>
      channelIds.hashCode ^
      length.hashCode ^
      sampleRateHz.hashCode ^
      frontDynamicSagMm.hashCode ^
      rearDynamicSagMm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuspensionEstimateMeta &&
          runtimeType == other.runtimeType &&
          channelIds == other.channelIds &&
          length == other.length &&
          sampleRateHz == other.sampleRateHz &&
          frontDynamicSagMm == other.frontDynamicSagMm &&
          rearDynamicSagMm == other.rearDynamicSagMm;
}
