// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mirror of [`idl_rs::spectrogram::SpectrogramResult`] for FRB codegen.
/// `power` is flat row-major `n_times × n_freqs`: frame `t`, bin `f` is at
/// `power[t * n_freqs + f]`. 2-D arrays cannot cross FRB, hence the flat
/// buffer + explicit dims.
class SpectrogramResult {
  final Float64List freqsHz;
  final Float64List timesSecs;
  final Float64List power;
  final int nTimes;
  final int nFreqs;

  const SpectrogramResult({
    required this.freqsHz,
    required this.timesSecs,
    required this.power,
    required this.nTimes,
    required this.nFreqs,
  });

  @override
  int get hashCode =>
      freqsHz.hashCode ^
      timesSecs.hashCode ^
      power.hashCode ^
      nTimes.hashCode ^
      nFreqs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpectrogramResult &&
          runtimeType == other.runtimeType &&
          freqsHz == other.freqsHz &&
          timesSecs == other.timesSecs &&
          power == other.power &&
          nTimes == other.nTimes &&
          nFreqs == other.nFreqs;
}
