// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Mirror of [`idl_rs::table::Cell`].
class Cell {
  final String? formula;
  final double? literal;
  final String? name;

  const Cell({
    this.formula,
    this.literal,
    this.name,
  });

  @override
  int get hashCode => formula.hashCode ^ literal.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cell &&
          runtimeType == other.runtimeType &&
          formula == other.formula &&
          literal == other.literal &&
          name == other.name;
}

/// Mirror of [`idl_rs::table::CellResult`].
class CellResult {
  final double? value;
  final String? error;

  const CellResult({
    this.value,
    this.error,
  });

  @override
  int get hashCode => value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CellResult &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          error == other.error;
}

/// Mirror of [`idl_rs::table::Column`].
class Column {
  final String id;
  final String? name;
  final String? template;

  const Column({
    required this.id,
    this.name,
    this.template,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ template.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Column &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          template == other.template;
}

/// Mirror of [`idl_rs::table::Row`].
class Row {
  final String id;
  final RowContext? context;

  const Row({
    required this.id,
    this.context,
  });

  @override
  int get hashCode => id.hashCode ^ context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Row &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          context == other.context;
}

/// Mirror of [`idl_rs::table::RowContext`].
class RowContext {
  final String sessionId;
  final int lapIndex;

  const RowContext({
    required this.sessionId,
    required this.lapIndex,
  });

  @override
  int get hashCode => sessionId.hashCode ^ lapIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RowContext &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          lapIndex == other.lapIndex;
}

/// Mirror of [`idl_rs::table::TableModel`].
class TableModel {
  final List<Column> columns;
  final List<Row> rows;
  final List<List<Cell>> cells;

  const TableModel({
    required this.columns,
    required this.rows,
    required this.cells,
  });

  @override
  int get hashCode => columns.hashCode ^ rows.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableModel &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows &&
          cells == other.cells;
}
