// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `into_core`

/// Detect ordered track visits for the retained session handle, using engine
/// default tuning. Identity (`visit_id`) is assigned app-side.
Future<List<VisitWindow>> detectVisits(
        {required SessionHandle handle, required List<TrackArg> tracks}) =>
    RustLib.instance.api
        .crateTracksDetectVisits(handle: handle, tracks: tracks);

/// Build the session's GPS polyline (for authoring a Track reference polyline).
Future<List<GpsFixArg>> gpsTrack({required SessionHandle handle}) =>
    RustLib.instance.api.crateTracksGpsTrack(handle: handle);

/// One value per GPS fix (in `gps_track` order): `channel_id` resampled to each
/// fix's instant. `NaN` where the channel is absent or the fix is outside its
/// span. Used to colour the GPS polyline by a channel value.
Future<Float64List> gpsChannelValues(
        {required SessionHandle handle, required String channelId}) =>
    RustLib.instance.api
        .crateTracksGpsChannelValues(handle: handle, channelId: channelId);

/// FFI GPS point (raw channel scale, degrees × 1e7). `timestamp_ms` is ignored
/// by detection but carried so the same struct serves `gps_track` authoring.
class GpsFixArg {
  final PlatformInt64 timestampMs;
  final double lat;
  final double lon;

  const GpsFixArg({
    required this.timestampMs,
    required this.lat,
    required this.lon,
  });

  @override
  int get hashCode => timestampMs.hashCode ^ lat.hashCode ^ lon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpsFixArg &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          lat == other.lat &&
          lon == other.lon;
}

/// One reference track to match against.
class TrackArg {
  final String trackId;
  final List<GpsFixArg> polyline;

  const TrackArg({
    required this.trackId,
    required this.polyline,
  });

  @override
  int get hashCode => trackId.hashCode ^ polyline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackArg &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          polyline == other.polyline;
}

class VisitWindow {
  final String trackId;
  final PlatformInt64 startTimestampMs;
  final PlatformInt64 endTimestampMs;

  const VisitWindow({
    required this.trackId,
    required this.startTimestampMs,
    required this.endTimestampMs,
  });

  @override
  int get hashCode =>
      trackId.hashCode ^ startTimestampMs.hashCode ^ endTimestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisitWindow &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          startTimestampMs == other.startTimestampMs &&
          endTimestampMs == other.endTimestampMs;
}
