// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Probe an `.mp4`/`.mov` container (SPEC §33.6 `video probe`, in-process).
Future<VideoInfo> videoProbe({required String path}) =>
    RustLib.instance.api.crateVideoVideoProbe(path: path);

/// Estimate the sync offset for `video_path` against the session: GPMF UTC
/// anchor when present, else container creation time. GPMF *absence* falls
/// through silently (normal); other errors surface. SPEC §33.3.
Future<VideoSyncOutcome> estimateVideoSync(
        {required SessionHandle handle, required String videoPath}) =>
    RustLib.instance.api
        .crateVideoEstimateVideoSync(handle: handle, videoPath: videoPath);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionHandle>>
abstract class SessionHandle implements RustOpaqueInterface {}

/// Error returned by the video bridge entry points.
class VideoFailure implements FrbException {
  final VideoFailureKind kind;
  final String message;

  const VideoFailure({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// Discriminant for [`VideoFailure`] — freezed-free error crossing (the
/// `ParseFailure` precedent). Mirrors `idl_rs::video::VideoErrorKind`.
enum VideoFailureKind {
  io,
  parse,
  noGpmf,
  noOverlap,
  export_,
  ;
}

/// Container facts for a video file (pure-Rust ISO-BMFF walk; no ffmpeg).
/// `fps` in frames/second, `duration_s` seconds, creation time in UTC ms.
class VideoInfo {
  final int width;
  final int height;
  final double fps;
  final double durationS;
  final PlatformInt64? creationTimeUtcMs;
  final bool hasGpmd;

  const VideoInfo({
    required this.width,
    required this.height,
    required this.fps,
    required this.durationS,
    this.creationTimeUtcMs,
    required this.hasGpmd,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      fps.hashCode ^
      durationS.hashCode ^
      creationTimeUtcMs.hashCode ^
      hasGpmd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fps == other.fps &&
          durationS == other.durationS &&
          creationTimeUtcMs == other.creationTimeUtcMs &&
          hasGpmd == other.hasGpmd;
}

/// How a sync offset was estimated. Plain unit enum → plain Dart enum.
enum VideoSyncMethod {
  gpmf,
  creationTime,
  ;
}

/// An estimated video↔session sync: `session_time_s = video_time_s +
/// offset_s`; confidence 0.9 (gpmf) / 0.3 (creation_time).
class VideoSyncOutcome {
  final double offsetS;
  final double confidence;
  final VideoSyncMethod method;

  const VideoSyncOutcome({
    required this.offsetS,
    required this.confidence,
    required this.method,
  });

  @override
  int get hashCode => offsetS.hashCode ^ confidence.hashCode ^ method.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoSyncOutcome &&
          runtimeType == other.runtimeType &&
          offsetS == other.offsetS &&
          confidence == other.confidence &&
          method == other.method;
}
